project:
  type: website

website:
  title: UFO Sightings
  navbar:
    right:
      - icon: github
        href: https://info-526-s24.github.io/project-01-fight-club/
    left:
      - text: Home Page
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
